name:                uKanren-transformation
version:             0.1.0.0
github:              "kajigor/uKanren-transformation"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2019 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/uKanren-transformation#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- process 
- temporary 
- text 
- fgl
- graphviz 
- mtl
- extra
- directory
- timeit
- tasty-discover

ghc-options:
  - -fwarn-unused-imports

library:
  source-dirs: 
  - src/

# executables:
#   uKanren-transformation-exe:
#     main:                Main.hs
#     source-dirs:
#     - app
#     - test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uKanren-transformation

tests:
  # uKanren-transformation-test:
  #   main:                CpdTests.hs
  #   source-dirs:         
  #   - test/
  #   - test/ocamlTest/
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - uKanren-transformation
  uKanren-transformation-test:
    main:                Test.hs
    source-dirs:         test/auto
    dependencies:
    - uKanren-transformation
    - hedgehog
    - HUnit
    - tasty
    - tasty-hedgehog
    - tasty-hunit